# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Care',
            fields=[
                ('care_id', models.IntegerField(primary_key=True, serialize=False)),
                ('care_theme', models.CharField(max_length=60)),
                ('care_way', models.CharField(max_length=60)),
                ('care_time', models.DateField()),
                ('care_nexttime', models.DateField()),
                ('care_remark', models.TextField()),
                ('care_is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_customer_care',
            },
        ),
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=60)),
                ('c_gender', models.CharField(max_length=60)),
                ('c_birthdate', models.DateField(blank=True, null=True)),
                ('c_mobile', models.CharField(max_length=60)),
                ('c_address', models.CharField(blank=True, max_length=60, null=True)),
                ('c_founder', models.CharField(max_length=60)),
                ('c_telephone', models.CharField(blank=True, max_length=60, null=True)),
                ('c_company', models.CharField(blank=True, max_length=60, null=True)),
                ('c_email', models.CharField(blank=True, max_length=254, null=True)),
                ('c_QQ', models.CharField(blank=True, max_length=60, null=True)),
                ('c_change_people', models.CharField(max_length=60)),
                ('c_weibo', models.CharField(blank=True, max_length=60, null=True)),
                ('c_MSN', models.CharField(blank=True, max_length=60, null=True)),
                ('c_createdate', models.DateTimeField(auto_now_add=True)),
                ('c_remark', models.TextField(blank=True, null=True)),
                ('c_profession', models.CharField(blank=True, max_length=60, null=True)),
                ('c_type', models.CharField(max_length=60)),
                ('c_is_delete', models.BooleanField(default=False)),
                ('cus_care', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db_manager.Customer_Care')),
            ],
            options={
                'db_table': 't_customer_info',
            },
        ),
        migrations.CreateModel(
            name='Customer_Source',
            fields=[
                ('c_source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_source_name', models.CharField(max_length=60)),
                ('c_source_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_customer_source',
            },
        ),
        migrations.CreateModel(
            name='customer_State',
            fields=[
                ('c_state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_state_name', models.CharField(max_length=60)),
                ('c_state_descripe', models.CharField(max_length=60)),
                ('c_state_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_customer_state',
            },
        ),
        migrations.CreateModel(
            name='Customer_Type',
            fields=[
                ('c_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_type_name', models.CharField(max_length=60)),
                ('c_type_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_customer_type',
            },
        ),
        migrations.CreateModel(
            name='Department_Info',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=60, null=True)),
                ('department_describe', models.CharField(blank=True, max_length=500, null=True)),
                ('department_delete', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 't_department',
            },
        ),
        migrations.CreateModel(
            name='Employee_Info',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_gender', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_age', models.IntegerField(blank=True, null=True)),
                ('employee_nation', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_wages_card', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_education', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_marry', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_address', models.CharField(blank=True, max_length=600, null=True)),
                ('employee_mobile', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_telephone', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_email', models.CharField(blank=True, max_length=250, null=True)),
                ('employee_identity_card', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_founder', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_account', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_password', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_hobby', models.CharField(blank=True, max_length=60, null=True)),
                ('employee_delete', models.NullBooleanField(default=False)),
                ('employee_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.Department_Info')),
            ],
            options={
                'db_table': 't_employee',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_address', models.CharField(blank=True, max_length=100, null=True)),
                ('house_price', models.FloatField(blank=True, null=True)),
                ('house_environment', models.CharField(blank=True, max_length=1000, null=True)),
                ('house_type', models.CharField(blank=True, max_length=100, null=True)),
                ('house_delete', models.NullBooleanField(default=False)),
                ('house_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.Employee_Info')),
            ],
            options={
                'db_table': 't_house',
            },
        ),
        migrations.CreateModel(
            name='House_Type',
            fields=[
                ('h_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_type_name', models.CharField(blank=True, max_length=60, null=True)),
                ('h_type_delete', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 't_house_type',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_theme', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_content', models.CharField(blank=True, max_length=6000, null=True)),
                ('notice_time', models.DateTimeField(auto_now_add=True)),
                ('notice_end_time', models.DateTimeField()),
                ('notice_man', models.CharField(blank=True, max_length=60, null=True)),
                ('notice_delete', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 't_notice',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=60, null=True)),
                ('role_grade', models.CharField(blank=True, max_length=60, null=True)),
                ('role_delete', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 't_role',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='house_housetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.House_Type'),
        ),
        migrations.AddField(
            model_name='employee_info',
            name='employee_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.Role'),
        ),
        migrations.AddField(
            model_name='customer_info',
            name='cus_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.Employee_Info'),
        ),
        migrations.AddField(
            model_name='customer_info',
            name='cus_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.Customer_Source'),
        ),
        migrations.AddField(
            model_name='customer_info',
            name='cus_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.customer_State'),
        ),
        migrations.AddField(
            model_name='customer_info',
            name='cus_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.Customer_Type'),
        ),
    ]
